name: CI
# If there is push to main, do this script
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "weather-bot-image"
  CONTAINER_NAME: "weather-bot-container"

jobs:
  build_and_push:
  # server type for job running
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
    
    # login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # create image and push it to container registry 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/weather-bot-image:latest

  deploy:
    runs-on: ubuntu-latest
      # deploy requires build_and_push completed
    needs: build_and_push

    steps:
      # connect to remote server via ssh
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          # just ip without http
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: IMAGE_NAME,CONTAINER_NAME
          script: |
            # Download image from docker hub
            docker pull sacrament0/$(echo $IMAGE_NAME)
            # Stop current docker container
            docker stop $(echo $CONTAINER_NAME)
            # Delete this container
            docker rm $(echo $CONTAINER_NAME)
            # Set env variables
            export TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            export OWM_API_KEY=${{ secrets.OWM_API_KEY }}
            # Start new container from downloaded image
            docker run -e TOKEN -e OWM_API_KEY -d \
            --restart always \
            --name $(echo $CONTAINER_NAME) \
            sacrament0/$(echo $IMAGE_NAME)
